### ISSUE TITLE
Include/exclude providers in options

### ISSUE THREAD

**Issue by raae** [lillylabs/gatsby-remark-oembed#11]
What options do we need?

My thoughts:
* white and/or blacklist of providers
* indicate the use of plain link: `https://www.youtube.com/embed/2Xc9gXyf2G4` or this style `oembed: https://www.youtube.com/embed/2Xc9gXyf2G4` or both

**Comment by raae** [comment]
Could you start looking at this @olavea ?

A first step would be to see if you can console log the option in the main function of the plugin. Ie. after this line `module.exports = async ({ markdownAST }) => {` in the index.js file.

To figure out how options work you can see if the plugin authoring docs have any info on it: https://next.gatsbyjs.org/docs/plugin-authoring/.

**Comment by raae** [comment]
We figured out options are sent as the second argument to, see pluginOptions `module.exports = async ({ markdownAST }, pluginOptions) =>`.

Later we need to use these options. I will make concrete tasks for doing this for @olavea .

**Comment by olavea** [comment]
Today I will: 
–try to remember what @raae showed me yesterday
–do what i remember a couple of times
–write up a sketchnote, take a photo of it and link to the photo here

**Comment by raae** [comment]
Today we will try to create a filter function that uses the whitelist option and only returns providers named in the filter function.

To prepare: 
- Do javascript30 array cardio: https://courses.wesbos.com/account/access/58a46a31daf7a2764345612a/view/194130346
- Focus on the filter of inventors examples
Then
- Checkout out branch origin/option-#11 by clicking the small master label in bottom left corner of vscode
- Find skeleton function I have created called filterProviders in helper.js.
- Inside plugin folder in console write `npm run test`and watch it not work.
- Try to create code to filter the provider list so only the ones with names found in whitelist is returned.

You will probably get stuck somewhere along the way and we will code it together when I get back.

**Comment by raae** [comment]
Moved "indicate the use of plain link: https://www.youtube.com/embed/2Xc9gXyf2G4 or this style oembed: https://www.youtube.com/embed/2Xc9gXyf2G4 or both" to its own issues. #23
